version: "3.2"
services:
  lighthouse:
    restart: always
    build:
      context: ../../
      dockerfile: ./docker/latest/lighthouse.Dockerfile
    environment:
      - NETWORK=mainnet
    volumes:
      - lighthouse_db:/root/.lighthouse
    ports:
      - 127.0.0.1:5052:5052
      - 9000:9000/udp
      - 9000:9000/tcp
    command: ["tail", "-f", "/dev/null"]

volumes:
  lighthouse_db:
