version: "3.2"
services:
  ipld-eth-db:
    restart: always
    build:
      context: ${vulcanize_ipld_eth_db}/
    environment:
      POSTGRES_USER: vdbm
      POSTGRES_DB: vulcanize_testing
      POSTGRES_PASSWORD: password
    volumes:
      - vdb_db_eth_server:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8077:5432"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  vdb_db_eth_server:
