version: "3.2"
services:
  # If you want prometheus to work, you must update the following file in the ops repo locally.
  # localhost:6060 --> go-ethereum:6060
  prometheus:
    restart: always
    user: "987"
    image: prom/prometheus
    volumes:
      - ${vulcanize_ops}/metrics/etc:/etc/prometheus
      - ./prometheus-data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
  grafana:
    restart: always
    user: "472"
    image: grafana/grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
